### ISSUE TITLE
Hello !! I have a question

### ISSUE THREAD

**Issue by qorgh346** [ShunChengWu/SceneGraphFusion#13]

**Comment by qorgh346** [comment]
Hello, 
Question 1. 
If the RGB image and Depth image are given in the GraphSLAM GUI system, will the segmentation function and scene reconstruction be performed?? 
If not , is it for drawing using datasets such as extension ply files and mesh files used in learning???

**Comment by qorgh346** [comment]
![image](https://user-images.githubusercontent.com/77768280/146182787-36ed2951-2184-462b-b014-06c1ccd6c5b9.png)

**Comment by ShunChengWu** [comment]
Hi, 
I am not quite sure that I understand your question. 
The segmentation method takes depth maps and outputs temporal consistent segmentations along with the reconstruction. 
The PLY file taken by the system is to render the depths since the original depth given by the 3RScan is in very low resolution. 
In your own application, you can write a custom data loader that uses the original depth from any source. But you may also need to adjust the parameters of the InSeg system in order to have a good segmentation output.

**Comment by qorgh346** [comment]
I want to operate the fusion system using my data.
In order to do that, can you know how to create your own data loader?

**Comment by qorgh346** [comment]
Thank you!!

**Comment by qorgh346** [comment]
Is there any way to operate the GraphSLAMGui system without using files such as labels.instances.annotated.v2.ply and mesh.refined.v2.obj using the existing 3RScan dataset?

**Comment by zhangguanghui1** [comment]
Hello! I can complete the make, when I run "./exe_GraphSLAM_GUI --pth_in ../data/3RScan/4acaebcc-6c10-2a2a-858b-29c7e4fb410d/sequence/ --pth_model ../CVPR21_traced/traced/" ,  only RGB and Depth graphs are displayed in the GUI system. I don't know how to solve it?  Could you help me?
![Screenshot from 2022-01-05 20-18-33](https://user-images.githubusercontent.com/28031977/148216739-2b83ef9a-1e9d-49d4-9983-e9ec65068386.png)

**Comment by ShunChengWu** [comment]
yes. of course. But the current system requires aligned RGB and depth images (in terms of their intrinsic). Feel free to modify the system accordingly. 
These two files are used to do get rendered depth.

**Comment by qorgh346** [comment]
yes!!! thank you!!
