### ISSUE TITLE
Is it ok without entering "pose"? The paper says that only RGBD is required

### ISSUE THREAD

**Issue by why-freedom** [ShunChengWu/SceneGraphFusion#8]
# If I annotate this paragraph, i.e. do not assign pose to inseg, the result will be messy，Why？Looking forward to your reply。

void GraphSLAM::ProcessFrame(int idx, const cv::Mat &colorImage, const cv::Mat &depthImage,const Eigen::Matrix4f *pose) {
    // if(pose){  // 此处pose给inseg，否则没有pose，inseg结果较差？ hy
    //     pose_ = *pose;
    //     inseg_->set_pose(pose_);
    // }
    mTimeStamp = idx;
    CTICK("[SLAM][ProcessFrame]1.ProcessFrame");
    ......

**Comment by ShunChengWu** [comment]
the front-end estimates pose with a relatively naive approach. you can replace the pose estimation from the InSeg system with other methods.

**Comment by stevenAce13** [comment]
Hi! Thanks for the work.

I've a similar question to this pose and looking forward to your comments :).

For this "pose" variable here, may we assume it's checking whether a ground-truth campose pose is given/provided outside to be set for the inseg? More specifically,
- If (pose is not None), then we use the ground-truth pose for a better reconstruction quality, ignoring the CamPose Estimation step in SLAM. 
- If (pose == 0), then we use Keller etal [19]'s SLAM approach to estimate a camera pose for further usage, which might be messy due to the outdated SLAM algorithm.

Keller et al. [19]: Real-Time 3D Reconstruction in Dynamic Scenes Using Point-Based Fusion. ([19] referenced from the paper [50] in SceneGraphFusion, which is "RealTime and Scalable Incremental Segmentation on Dense SLAM".)

**Comment by ShunChengWu** [comment]
exactly.
